import Head from "next/head";
import { Flex, Heading } from "@chakra-ui/react";
import { useState, useEffect } from "react";
import React from "react";
import Layout from "@/components/Layout/Layout";
import Todolist from "@/components/Todolist/Todolist";
import Countdown from "@/components/Others/Countdown";
import AddTodo from "@/components/Todolist/AddTodo";


export default function Home() {
  const [number, setNumber] = useState(5);
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    console.log("La page vient d'être chargée");
  }, []);

  useEffect(() => {
    console.log("nombre vient de changer");
  }, [number]);

  useEffect(() => {
    console.log("quelque chose a changé dans l'app");
  });

  return (
    <>
      <Head>
        <title>React tuto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout number={number} setNumber={setNumber}>
        <Flex p="5rem" justifyContent="space-between">
          <Flex
            alignItems="center"
            direction="column"
            justifyContent={"center"}
          >
            <Heading mb="2rem">
              Countdown from soutenance
            </Heading>
            <Countdown targetDate="2023-02-24" />
          </Flex>
          <Flex
            alignItems="center"
            w="100%"
            direction="column"
            justifyContent={"center"}
          >
            <Heading as="h1" mb="2rem">
              Todolist
            </Heading>
            <AddTodo todos={todos} setTodos={setTodos} />
            <Todolist todos={todos} setTodos={setTodos} />
          </Flex>
        </Flex>
      </Layout>
    </>
  );
}
